#:kivy 1.0.9
# THE CLIENT LAYOUT FILE

FloatLayout:
    Image:
        id: image1
        source: "media/test1.jpg"
        keep_ratio: True
        allow_stretch: True

    Image:
        id: image2
        source: "media/test3.jpg"
        keep_ratio: True
        allow_stretch: True
        opacity: 0.5

    Video:
        id: video
        source: "media/test1.mp4"
        state: 'play'
        eos: 'loop'
        keep_ratio: True
        allow_stretch: True